# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout somewhen, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# font for window titles. ISO 10646 = Unicode
font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
#font -schumacher-clean-medium-r-normal--14-140-75-75-c-70-iso646.1991-irv
#font -dec-terminal-medium-r-normal--14-140-75-75-c-80-iso8859-1
#font -b&h-lucidatypewriter-medium-r-normal-sans-12-120-75-75-m-70-iso10646-1
font -b&h-lucida-medium-r-normal-sans-12-120-75-75-p-71-iso10646-1
#font pango:Press Start 2P 10px
#font pango:Liberation Sans 10
#font pango:Lato Medium 10
#font pango:Terminus (TTF) Medium 9

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal
bindsym $mod+Shift+Return exec xfce4-terminal --role floating_term
for_window [window_role=floating_term] floating enable

# kill focused window
bindsym $mod+Shift+Q kill

# start dmenu (a program launcher)
#bindsym $mod+d exec dmenu_run

# start rofi (another program launcher)
bindsym $mod+d exec "rofi -show run -matching fuzzy"

# start thunar (xfce file manager)
#bindsym $mod+e exec "thunar"

# lock screen
#bindsym $mod+l exec i3_lock.sh

# lock and suspend
#bindsym $mod+Shift+L exec i3_lock_and_suspend.sh

# change focus
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

#bindsym $mod+h focus left
#bindsym $mod+j focus down
#bindsym $mod+k focus up
#bindsym $mod+l focus right

# move focused window
#bindsym $mod+Shift+J move left
#bindsym $mod+Shift+K move down
#bindsym $mod+Shift+L move up
#bindsym $mod+Shift+Oslash move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen

# toggle borders of current window
bindsym $mod+Shift+B border toggle

# change container layout (stacked, tabbed, default)
#bindsym $mod+s layout stacking
#bindsym $mod+w layout tabbed
#bindsym $mod+e layout default

# toggle sticky window
bindsym $mod+w sticky toggle

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+Control+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindcode $mod+d focus child

# switch to workspace
bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+4 workspace number 4
bindsym $mod+5 workspace number 5
bindsym $mod+6 workspace number 6
bindsym $mod+7 workspace number 7
bindsym $mod+8 workspace number 8
bindsym $mod+9 workspace number 9
bindsym $mod+0 workspace number 10

# Move back to the previous workspace
workspace_auto_back_and_forth no

# Move to next workspace
bindsym $mod+n workspace next
bindsym $mod+Shift+N workspace prev

bindsym Shift+Control+$mod+Left move workspace to output left
bindsym Shift+Control+$mod+Right move workspace to output right
bindsym Shift+Control+$mod+Up move workspace to output up
bindsym Shift+Control+$mod+Down move workspace to output down

bindsym Mod1+Tab workspace back_and_forth

# move focused container to workspace
bindcode $mod+Shift+10 move workspace 1
bindcode $mod+Shift+11 move workspace 2
bindcode $mod+Shift+12 move workspace 3
bindcode $mod+Shift+13 move workspace 4
bindcode $mod+Shift+14 move workspace 5
bindcode $mod+Shift+15 move workspace 6
bindcode $mod+Shift+16 move workspace 7
bindcode $mod+Shift+17 move workspace 8
bindcode $mod+Shift+18 move workspace 9
bindcode $mod+Shift+19 move workspace 10

# reload the configuration file
bindsym $mod+Shift+C reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+R restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+E exit

# resize window (you can also use the mouse for that)
mode "resize" {
# These bindings trigger as soon as you enter the resize mode
# They resize the border in the direction you pressed, e.g.
# when pressing left, the window is resized so that it has
# more space on its left
bindsym Left resize shrink left 5 px or 5 ppt
bindsym Shift+Left resize grow   left 5 px or 5 ppt

bindsym Down resize shrink down 5 px or 5 ppt
bindsym Shift+Down resize grow   down 5 px or 5 ppt

bindsym Up resize shrink up 5 px or 5 ppt
bindsym Shift+Up resize grow   up 5 px or 5 ppt

bindsym Right resize shrink right 5 px or 5 ppt
bindsym Shift+Right resize grow   right 5 px or 5 ppt

# back to normal: Enter or Escape
bindsym Return mode "default"
bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
client.urgent #2f343a #900000 #ffffff
bar {
    #mode hide
    hidden_state hide
    #status_command i3status
    status_command i3_status.sh
	colors {
	    urgent_workspace #2f343a #900000
	}
    tray_output none
    #output primary
}

#for_window [class="Google-chrome"] border none
#for_window [class="Chromium-browser"] border none

#bindsym Control+Mod1+e exec --no-startup-id nautilus --no-desktop
bindsym $mod+l exec --no-startup-id i3_lock.sh
#bindsym Control+Mod1+w exec --no-startup-id google-chrome

#exec --no-startup-id xrandr --output CRT2 --auto --primary --mode 1920x1200 --pos 0x140 --output DFP2 --auto --mode 1920x1200 --pos 1920x0 --rotate left

#exec --no-startup-id feh --bg-scale Pictures/color-wave-dual-screen-162256.jpg
exec --no-startup-id feh --bg-scale Pictures/wp8018051.jpg

#exec --no-startup-id dropbox start
#exec --no-startup-id xrandr --dpi 142
#exec --no-startup-id keyboard.sh
#exec --no-startup-id touchpad.sh
#exec --no-startup-id sudo modprobe bbswitch
#exec --no-startup-id volumeicon
#exec --no-startup-id nm-applet
#exec --no-startup-id k810.sh
#exec --no-startup-id k810_watcher.sh

# This is now done in /etc/X11/xorg.conf.d/40-varmilo.conf
#exec --no-startup-id setxkbmap -layout us,no -option 'grp:alt_shift_toggle,caps:escape'
#exec --no-startup-id setxkbmap -layout us,no -variant altgr-intl -option 'caps:escape,compose:ralt'
#exec --no-startup-id xmodmap -e "keysym Alt_R = Multi_key"

# Change keyboard layout and restart i3status to reflect change immediately
bindsym Mod4+space exec --no-startup-id "xkb-switch -n; pkill -x --signal=SIGUSR1 i3status"

bindsym Shift+Control+$mod+R exec i3-input -F 'rename workspace to %s' -P 'New name: '

#bindsym $mod+Pause exec --no-startup-id dbus-send --print-reply=literal --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
#bindsym XF86AudioPlay exec --no-startup-id dbus-send --print-reply=literal --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
bindsym XF86AudioPlay exec --no-startup-id i3_status_refresh.sh playerctl play-pause
bindsym --whole-window --border $mod+button10 exec --no-startup-id i3_status_refresh.sh playerctl play-pause
#bindsym XF86AudioStop exec --no-startup-id dbus-send --print-reply=literal --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop
bindsym XF86AudioStop exec --no-startup-id i3_status_refresh.sh playerctl stop
#bindsym $mod+Scroll_Lock exec --no-startup-id dbus-send --print-reply=literal --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
#bindsym XF86AudioNext exec --no-startup-id dbus-send --print-reply=literal --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
bindsym XF86AudioNext exec --no-startup-id i3_status_refresh.sh playerctl next
bindsym Shift+XF86AudioPlay exec --no-startup-id i3_status_refresh.sh playerctl next
bindsym --whole-window --border $mod+button9 exec --no-startup-id i3_status_refresh.sh playerctl next
#bindsym $mod+Print exec --no-startup-id dbus-send --print-reply=literal --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
#bindsym XF86AudioPrev exec --no-startup-id dbus-send --print-reply=literal --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
bindsym XF86AudioPrev exec --no-startup-id i3_status_refresh.sh playerctl previous
bindsym --whole-window --border $mod+button8 exec --no-startup-id i3_status_refresh.sh playerctl previous

bindsym --whole-window --border $mod+button4 exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10%
bindsym --whole-window --border $mod+button5 exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10%
bindsym --whole-window --border $mod+button2 exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10%
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle

bindsym Shift+$mod+F12 exec --no-startup-id xbacklight -inc 1
bindsym Shift+$mod+F11 exec --no-startup-id xbacklight -dec 1

bindsym Shift+$mod+I exec --no-startup-id invert.sh

#bindsym Print exec --no-startup-id gnome-screenshot -i
bindsym Print exec --no-startup-id xfce4-screenshooter
bindsym Shift+Mod1+3 exec --no-startup-id xfce4-screenshooter --fullscreen
bindsym Shift+Mod1+4 exec --no-startup-id xfce4-screenshooter --region
bindsym Shift+Mod1+5 exec --no-startup-id xfce4-screenshooter --window

for_window [class="srlookup-cli-Program"] floating enable
bindsym Control+Shift+Mod1+S exec --no-startup-id SRLookup

for_window [class="Galculator"] floating enable
for_window [class="KeePassXC"] floating enable
#for_window [class="gfsokoban-Main"] floating enable
